### ISSUE TITLE
[feature]BCS是如何规划'模板集'市场的？

### ISSUE THREAD

**Issue by pythonton** [Tencent/bk-bcs#123]
**feature相关背景与描述**
BCS在考虑功能设计时，可能需要关注场景化的应用，如何通过**开箱即用的模板集**让用户快速体验BCS，以及恰好解决了一个小的痛点（比如gitlab-ce），让其深入的使用。

**解决方案描述**
看图，不说话，用心去感受，😃。

- **阿里云**
![image](https://user-images.githubusercontent.com/50493427/61935643-82398c00-afbd-11e9-9564-11e86ecc387a.png)
![image](https://user-images.githubusercontent.com/50493427/61935666-92516b80-afbd-11e9-91c8-58d328b903c1.png)
- **GCP**
[请参照我的留言](https://github.com/Tencent/bk-bcs/issues/83)

**Comment by jamesgetx** [comment]
@pythonton 这个建议不错，我们后续会规划模板集市场功能，支持用户跨项目共享公共模板集

**Comment by pythonton** [comment]
> @pythonton 这个建议不错，我们后续会规划模板集市场功能，支持用户跨项目共享公共模板集

@jamesgetx nice
是否有考虑，模板集市场是公网访问的，类似阿里云、GCP这样，而不是私有环境下的模板集？

PS : 私有环境的模板集，意义不是太大，除非是像BAT这样的大公司，有N多个部门协同才有效果，关键是又有多少BAT这种规模的公司呢？😃
