### ISSUE TITLE
[feature]mesos loadbalance支持更多参数可配置

### ISSUE THREAD

**Issue by abstractmj** [Tencent/bk-bcs#131]
**feature相关背景与描述**
loadbalance中haproxy和nginx模版可配置参数较少，无法满足各种应用场景

**解决方案描述**
增加可配置参数，举例如下，后续补充：
- 是否打开访问日志
- 是否打开ssh
- 重试次数
- 最大连接数
- 超时时间
- 是否开启健康检查
- 健康检查具体参数配置
- 负载均衡策略配置
- （后续继续补充）

lb实例通用配置实现方式：
1. lb json的环境变量
2. lb json的annotation

具体frontend和backend的配置方式：
1. service json的annotation

**Comment by DeveloperJim** [comment]
Mesos方式也可以通过CRD来实现？
