### ISSUE TITLE
bcs-webconsole 添加 metrics接口

### ISSUE THREAD

**Issue by ifooth** [Tencent/bk-bcs#1493]
# bcs-webconsole服务metrics指标

###  bkbcs_webconsole_api_request_total_num
* 标识bcs-web-console服务API请求数指标
* label：handler, method, status

### bkbcs_webconsole_api_request_latency_time
* 标识bcs-web-console服务API的延迟指标
* label：handler, method, status 

### bkbcs_webconsole_pod_create_duration_seconds_count
* 标识bcs-web-console创建pod数量
* label:namespace, name, status

### bkbcs_webconsole_pod_create_duration_seconds_max
* 创建pod最大时间
* lable:namespace, name, status

### bkbcs_webconsole_pod_create_duration_seconds_min
* 创建pod最小时间
* lable:namespace, name, status

### bkbcs_webconsole_pod_create_duration_seconds_bucket
* 标识bcs-web-console pod创建耗费时间
* lable:namespace, name, status

### bkbcs_webconsole_pod_delete_duration_seconds_bucket
* 清除pod耗费时间
* lable:namespace, name, status

### bkbcs_webconsole_pod_delete_duration_seconds_max
* 清除pod最大时间
* lable:namespace, name, status

### bkbcs_webconsole_pod_delete_duration_seconds_min
* 清除pod最小时间
* lable:namespace, name, status

### bkbcs_webconsole_ws_connection_num
* 标识 websocke 连接数
* label: handler

#### bcs-webconsole API接口维度指标聚合
```
接口维度请求总数
sum(bkbcs_webconsole_api_request_total_num{}) by(handler)
 
接口维度时延
(sum(bkbcs_webconsole_api_request_latency_time) by (handler)) / (sum(bkbcs_webconsole_api_request_total_num) by (handler))
 
接口维度qps
sum(rate(bkbcs_webconsole_api_request_total_num[5m])) by (handler)

接口维度成功率
sum(bkbcs_webconsole_api_request_total_num{status="success"}) by(handler) / sum(bkbcs_webconsole_api_request_total_num) by(handler)
``` 

#### bcs-webconsole API接口方法维度指标聚合
```
接口方法维度请求总数
sum(bkbcs_webconsole_api_request_total_num{}) by(handler,method)
 
接口方法维度时延
(sum(bkbcs_webconsole_api_request_latency_time) by (handler,method)) / (sum(bkbcs_webconsole_api_request_total_num) by (handler,method))
 
接口方法维度qps
sum(rate(bkbcs_webconsole_api_request_total_num[5m])) by (handler,method)

接口方法维度成功率
sum(bkbcs_webconsole_api_request_total_num{status="success"}) by(handler,method) / sum(bkbcs_webconsole_api_request_total_num) by(handler,method)
```

#### bcs-webconsole pod维度指标聚合

```
pod 创建成功次数
sum(bkbcs_webconsole_pod_create_duration_seconds_count{status="success"})

pod 创建失败次数
sum(bkbcs_webconsole_pod_create_duration_seconds_count{status="failure"})

pod 创建成功耗时(s)分布
sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status="success"}) by(le)

pod 创建失败耗时(s)分布
sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status="failure"}) by(le)

pod 删除成功耗时(s)分布
sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status="failure"}) by(le)

pod 删除失败耗时(s)分布
sum(bkbcs_webconsole_pod_create_duration_seconds_bucket{status="failure"}) by(le)

当前pod数量
sum(bkbcs_webconsole_pod_create_duration_seconds_count{status="success"}) - 
sum(bkbcs_webconsole_pod_create_duration_seconds_count{status="failure"})

pod创建耗时极值情况
{{status}}_max: max(bkbcs_webconsole_pod_create_duration_seconds_max) by(status) {{status}}_min: min
(bkbcs_webconsole_pod_create_duration_seconds_min) by(status) 

pod删除耗时极值情况
{{status}}_max: max(bkbcs_webconsole_pod_delete_duration_seconds_max) by(status) {{status}}_min: min
(bkbcs_webconsole_pod_delete_duration_seconds_min) by(status) 

```

#### bcs-webconsole ws连接维度指标聚合
```
bcs-webconsole websocket连接次数
sum(bkbcs_webconsole_ws_connection_num{}) by(handler)

```

**Comment by ifooth** [comment]
- bkbcs_webconsole_ws_connection_num 应该是当前连接数吧， 加一个namespace, name label 表明哪些pod有流量， handler应该只有一个，可以去掉
- duration_seconds_count/sum/bucket是配套的，可以都加上

**Comment by linfang-canway** [comment]
grafana dashboard截图如下
![screencapture-127-0-0-1-3000-d-ljzTKRs7k-bcs-webconsole-2022-03-25-18_17_08](https://user-images.githubusercontent.com/86582008/160102694-477e3e0f-81f7-49e8-ab52-93617e766de5.png)
