### ISSUE TITLE
注册已有的k8s集群到bcs平台遇到注册成功但无法展示的问题

### ISSUE THREAD

**Issue by MirrorTown** [Tencent/bk-bcs#186]
根据https://github.com/Tencent/bk-bcs/blob/master/docs/features/k8s/%E5%9F%BA%E4%BA%8Ek8s%E7%9A%84%E5%AE%B9%E5%99%A8%E7%BC%96%E6%8E%92.md 该文档，执行了"纳管已有 k8s 集群"。并可以通过http://X.X.X.X:8080/tunnels/clusters/XX/version查看到集群版本信息。但无法在web页面的集群栏中看到注册的集群

**Comment by MirrorTown** [comment]
在自建集群部署的datawatch，抱了如下日志：
I0910 03:03:10.824594       1 writer.go:90] Writer starting ReplicationController data channel
I0910 03:03:10.825026       1 writer.go:90] Writer starting Namespace data channel
I0910 03:03:10.825034       1 writer.go:90] Writer starting ExportService data channel
I0910 03:03:10.825040       1 writer.go:90] Writer starting Node data channel
I0910 03:03:10.825046       1 writer.go:90] Writer starting ConfigMap data channel
I0910 03:03:10.825052       1 writer.go:90] Writer starting Deployment data channel
I0910 03:03:10.825057       1 writer.go:90] Writer starting Ingress data channel
I0910 03:03:10.825063       1 writer.go:90] Writer starting Pod data channel
I0910 03:03:10.825071       1 writer.go:90] Writer starting Secret data channel
I0910 03:03:10.825077       1 writer.go:90] Writer starting Event data channel
I0910 03:03:10.825083       1 writer.go:90] Writer starting Job data channel
I0910 03:03:10.825088       1 writer.go:90] Writer starting EndPoints data channel
I0910 03:03:10.825094       1 writer.go:90] Writer starting DaemonSet data channel
I0910 03:03:10.825115       1 writer.go:90] Writer starting StatefulSet data channel
I0910 03:03:10.825123       1 writer.go:90] Writer starting ReplicaSet data channel
I0910 03:03:10.825131       1 writer.go:98] Writer ready to go into worker!
E0910 03:03:10.826104       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.Event: the server rejected our request for an unknown reason (get events)
I0910 03:03:10.824667       1 cluster.go:272] Cluster start list-watcher for: EndPoints
I0910 03:03:10.826975       1 cluster.go:272] Cluster start list-watcher for: DaemonSet
I0910 03:03:10.826984       1 cluster.go:272] Cluster start list-watcher for: Ingress
I0910 03:03:10.826996       1 synchronizer.go:37] wait for datawatcher to be ready
E0910 03:03:10.826430       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.Node: the server rejected our request for an unknown reason (get nodes)
E0910 03:03:10.826469       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.ReplicationController: the server rejected our request for an unknown reason (get replicationcontrollers)
E0910 03:03:10.826520       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.Service: the server rejected our request for an unknown reason (get services)
E0910 03:03:10.826563       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.Secret: the server rejected our request for an unknown reason (get secrets)
E0910 03:03:10.826681       1 reflector.go:134] bk-bcs/bcs-k8s/k8s-watch/app/k8s/watcher.go:110: Failed to list *v1.Namespace: the server rejected our request for an unknown reason (get namespaces)
这是什么原因

**Comment by bryanhe-bupt** [comment]
https://github.com/Tencent/bk-bcs/blob/master/docs/features/k8s/%E5%9F%BA%E4%BA%8Ek8s%E7%9A%84%E5%AE%B9%E5%99%A8%E7%BC%96%E6%8E%92.md
这篇文档中目前描述的是如果在bcs的后台bk-bcs上纳管已有k8s集群，在产品层面的bk-bcs-saas上纳管已有k8s集群的功能，还在排期实现当中。
开发完后，我们会及时同步到文档当中，感谢关注和支持。

**Comment by MirrorTown** [comment]
好的， 另外问下之后会对比如阿里云的容器服务或则腾讯云的k8s服务也可以在bcs管理平台管理吗？如果有大概什么时候会推出版本

**Comment by jiezinaxumi** [comment]
纳管已有k8s集群，页面层面上啥时候可以推出

**Comment by DeveloperJim** [comment]
@jiezinaxumi SAAS的需求可以提交到bk-bcs-saas issue列表中，一起推动解决。
