### ISSUE TITLE
调用scheduler部分api接口出现url not found

### ISSUE THREAD

**Issue by MirrorTown** [Tencent/bk-bcs#200]
http://X.X.X.X:8080/bcsapi/v4/scheduler/k8s/cluster/endpoints
header:
{
    BCS-ClusterID:  XXXX
}
Response:
{
  "result": false,
  "message": "url not found, please check k8s api docs",
  "code": 4001,
  "data": null
 }
这个是和k8s版本有关系还是项目本身的问题

**Comment by jiezinaxumi** [comment]
我也碰到相同的问题，k8s api请求路径不对，没有cluster path。

{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/version"
  ]
}

**Comment by DeveloperJim** [comment]
当前k8s版本的列表：1.5.x-1.12.x
如果不在该范围内，k8s转发会有以上报错。
