### ISSUE TITLE
[bug]构建执行make命令是报错，缺少依赖包。

### ISSUE THREAD

**Issue by KingDragon-Baron** [Tencent/bk-bcs#215]
问题描述
===========
go vet
../bcs-common/common/conf/types.go:29:2: cannot find package "github.com/bitly/go-simplejson" in any of:
        /root/go/src/bk-bcs/vendor/github.com/bitly/go-simplejson (vendor tree)

重现方法
================
centos7系统中，go编译环境，在bk-bcs目录下构建执行make

关键信息
=========
&amp;lt;!--  **重要提醒**: 这些关键信息会辅助我们快速定位问题。 --&amp;gt;

请提供以下信息:

 - [x] bk-bcs   版本: 
Version  : v1.13.5
BuildTime: 2019-09-29T11:29:27+0800
GitHash  : b129f09
 - [ ] 操作系统      : CentOS Linux release 7.4.1708 (Core)
 - [ ] bk-bcs 异常日志
无

**Comment by DeveloperJim** [comment]
https://github.com/Tencent/bk-bcs/blob/master/docs/install/source_compile.md
