### ISSUE TITLE
[feature]bcs-api support whitelist for auth check

### ISSUE THREAD

**Issue by Lwxiang** [Tencent/bk-bcs#224]
demands:
- auth check via bcs_token and configure auth in bcs-api's config_file.json
- support skip auth check when none bcs_token provided

**Comment by Lwxiang** [comment]
### bcs-api配置

```json
{
  ...
  "bkiam_auth": {
    "auth": true,
    "remote_check": false,
    "skip_none_token": true,
    "bkiam_auth_token_whitelist": [
      {
      	"token": "yOC29gI8SE2InoiU26Se387asAksENbJ",
      	"scope": [
          {
            "cluster_id": "BCS-MESOS-10032",
            "namespace": []
          }
      	]
      },
      {
      	"token": "MSqgEngkyNo7lEANHphHrQ==",
      	"scope": [
          {
            "cluster_id": "BCS-MESOS-10054",
            "namespace": ["gamesvr", "login"]
          }
      	]
      }
    ]
  }
  ...
}
```

- auth: 鉴权总开关，auth=true表示开启鉴权
- remote_check: 是否启用第三方校验，如权限中心
- skip_none_token: 是否跳过不含token的请求
- bkiam_auth_token_whitelist: token白名单配置
   - token: bcs-encrypt 加密后的token
   - scope: 权限范围，若空则适用所有cluster，若某个cluster下namespace为空则适用所有namespace

### bcs-client配置

```json
{
  ...
  "bcs_token": "X6RDn2JJXmXX5BPP"
  ...
}
```

- bcs_token: 真实的token

**Comment by DeveloperJim** [comment]
@Lwxiang 所有namespace资源如何进行配置？
