### ISSUE TITLE
[bug]纳管k8s集群正常，但纳管openshift集群异常

### ISSUE THREAD

**Issue by jiezinaxumi** [Tencent/bk-bcs#237]
问题描述
===========
在openshift master上纳管master，datawatch与bcs-k8s-driver 正常运行，
通过调用bcs-api返回
curl -v -X GET -H "Content-Type: application/json" -H "Authorization: Bearer umcEB9RwjBnnT96ZVlgr8Z3zXszN6qpT" http://api.bcs.service.consul:8080/bcsapi/v4/scheduler/k8s/namespaces -H 'BCS-ClusterID: BCS-K8S-40006' 
{
  "result": false,
  "message": "url not found, please check k8s api docs",
  "code": 4001,
  "data": null
 }
 发现bcs-k8s-driver 日志：
I1024 20:32:58.378364   16879 k8s-actions.go:122] client 172.16.200.40:35122 request /bcsapi/v4/scheduler/k8s/namespaces
I1024 20:32:58.378401   16879 k8s-actions.go:84] do request to url(https://172.16.7.24:8085/k8sdriver/v4/namespaces), method(GET)
I1024 20:32:58.378407   16879 k8s-actions.go:97] =============1========
I1024 20:32:58.394521   16879 k8s-actions.go:104] ============={
  "result": false,
  "message": "url not found, please check k8s api docs",
  "code": 4001,
  "data": null
 }========

关键信息
================
bcs-k8s-driver 启动参数：
./bcs-k8s-driver --address=172.16.7.24 --secure-port 8085 --kube-master-url=https://172.16.7.24:8443 --kube-ca-file /etc/origin/master/ca.crt --kube-cert-file /etc/origin/master/admin.crt --kube-key-file /etc/origin/master/admin.key --host-ip=172.16.7.24 --server-ca-file=/data/bkce/cert/bcs/bcs-ca.pem --server-cert-file=/data/bkce/cert/bcs/bcs-server.pem --server-key-file=/data/bkce/cert/bcs/bcs-server-key.pem --zk-url=172.16.200.40:2181,172.16.200.41:2181,172.16.200.42:2181 --custom-report-address= --custom-report-port=0 --custom-cluster-id=BCS-K8S-40006

 - [x] bk-bcs   版本: 
Version  : v1.13.3
 --&amp;gt;
 - [x] 操作系统      : Centos 7 x64

**Comment by jiezinaxumi** [comment]
另：bcs-k8s-driver 没代码，没文档，请问预计什么时候可以开源呢？谢谢

**Comment by DeveloperJim** [comment]
https://github.com/Tencent/bk-bcs/blob/master/docs/features/k8s/%E5%9F%BA%E4%BA%8Ek8s%E7%9A%84%E5%AE%B9%E5%99%A8%E7%BC%96%E6%8E%92.md#%E7%BA%B3%E7%AE%A1%E5%B7%B2%E6%9C%89-k8s-%E9%9B%86%E7%BE%A4

**Comment by jiezinaxumi** [comment]
> k8s集群纳管在1.13.x版本已经切换为kube-agent的方式。
> 相关手动管理的方式请参照：
> https://github.com/Tencent/bk-bcs/blob/master/docs/features/k8s/%E5%9F%BA%E4%BA%8Ek8s%E7%9A%84%E5%AE%B9%E5%99%A8%E7%BC%96%E6%8E%92.md#%E7%BA%B3%E7%AE%A1%E5%B7%B2%E6%9C%89-k8s-%E9%9B%86%E7%BE%A4

3ks，一开始走的就是采用手工纳管，前端发出的请求http://api.bcs.service.consul:8080/bcsapi/v4/scheduler/k8s/，  经过bcs-api 的proxy代理到BCS_MODULE_K8SAPISERVER，还是会转发到bcs-k8s-driver，所以proxy代理逻辑或者前端的K8s请求的path，需要修改

**Comment by DeveloperJim** [comment]
对于bcs-api，当前功能上bcs-k8s-driver和bcs-k8s-agent两套逻辑都有。
如果只是纯后台应用，使用k8s-agent就能兼容kubectl直连bcs-api。
如果使用bcs-saas来链接，确实需要走k8s-driver。当前saas开源部分暂未涉及agent的对接。
未来两周我们会正式发布1.14.5。我们可以将k8s-driver开源出来

**Comment by jiezinaxumi** [comment]
> 对于bcs-api，当前功能上bcs-k8s-driver和bcs-k8s-agent两套逻辑都有。
> 如果只是纯后台应用，使用k8s-agent就能兼容kubectl直连bcs-api。
> 如果使用bcs-saas来链接，确实需要走k8s-driver。当前saas开源部分暂未涉及agent的对接。
> 未来两周我们会正式发布1.14.5。我们可以将k8s-driver开源出来

期待1.14.5，以及k8s-driver的开源，感谢您的努力

**Comment by DeveloperJim** [comment]
@jiezinaxumi 
1.14.5的Prerelease版本已经发布，如果当前driver不支持的转发版本，
可以参考：https://github.com/Tencent/bk-bcs/blob/1.14.x/bcs-k8s/bcs-k8s-driver/kubedriver/versions/metaurls.go
