### ISSUE TITLE
[feature] mesos资源限制支持request、limit两种模式

### ISSUE THREAD

**Issue by zmberg** [Tencent/bk-bcs#27]
目前mesos资源限制只支持request方式，也就是cpu_shares方式。
但是有些业务需要quota方式的资源限制。

方案：
mesos资源限制支持两种模式：
request方式：cpu_shares限制，软限制
limit方式：cpu_quota限制，硬限制

**Comment by DeveloperJim** [comment]
功能已合并，issue关闭
