### ISSUE TITLE
处于更新状态的应用，允许手动重新调度其中的容器

### ISSUE THREAD

**Issue by zmberg** [Tencent/bk-bcs#29]
在引用滚动更新的过程中，如果存在lost状态的容器，则滚动更新无法继续执行，需要业务自行确认处理。

策略：
滚动更新过程中，处理lost状态的容器，业务能够执行手动重新调度，进而滚动更新能够继续执行

**Comment by DeveloperJim** [comment]
已合并，问题关闭
