### ISSUE TITLE
[bug] 容器自定义command命令执行结果没有保存

### ISSUE THREAD

**Issue by zmberg** [Tencent/bk-bcs#30]
问题描述
===========
业务自定义容器command命令，执行完毕后发现没有返回执行结果。
通过排查发现executor上报了执行结果，但是scheduler并没有存储到zk上面，导致执行结果丢失。

原因：
通过排查定位发现，是由于save  task command结果时没有对command加锁，导致并发情况下存在脏数据。

方案：
save command时增加互斥锁

**Comment by DeveloperJim** [comment]
已合并，问题关闭
