### ISSUE TITLE
[bug] 取消deployment滚动升级存在超时的情况

### ISSUE THREAD

**Issue by zmberg** [Tencent/bk-bcs#42]
问题描述
===========
在取消滚动升级的操作时，会先判断滚动升级是否处于delete old taskgroup的过程中，如果在此过程中，则会尝试等待重试30s，但是前端在调用此接口设置timeout为20s，因此在某些特殊情况下存在超时的情况。

**Comment by DeveloperJim** [comment]
特性已合并，issue关闭
