### ISSUE TITLE
[feature] BCS Mesos 集群 Framework 选择哪一种呢？

### ISSUE THREAD

**Issue by sober-wang** [Tencent/bk-bcs#421]
**feature相关背景与描述**
（清晰描述相关问题，是否有关联的issue）
 BCS Mesos 集群 Framework 选择哪一种呢？
是 Marathon 吗？

**Comment by DeveloperJim** [comment]
BCS中Mesos集群方案是基于Mesos系统扩展了自研的容器调度framework，其代码在bcs-mesos/bcs-scheduler。

**Comment by sober-wang** [comment]
谢谢。等有空了我也看一下，学习学习。
