### ISSUE TITLE
[Question]集群模式是否支持docker swarm

### ISSUE THREAD

**Issue by lfc3249635** [Tencent/bk-bcs#425]
请问集群模式是否支持docker swarm

**Comment by DeveloperJim** [comment]
项目早期有过类似的考虑，但是由于docker swarm暂无用户选择最终搁置。
当前的整体架构上是允许针对不同的调度平台进行集成，K8S和Mesos的兼容就是比较好的例子。
扩展上有两个实现方式：
> 1. 增加docker swarm driver，将bcs内部容器数据结构翻译成docker swarm结构，借助swarm api进入 该集群并实现容器管理。该方案需要进行一定兼容性调研

> 2. 当前网关增加对docker swarm多集群管理的透明转发能力，达到容器多集群协调管理能力

短期内我们暂时没有考虑支持docker swarm的特性，如果贵方有兴趣，欢迎方案共建与PR

**Comment by DeveloperJim** [comment]
近一月无回复，关闭
