### ISSUE TITLE
可以管理二进制部署好的kubernetes集群吗

### ISSUE THREAD

**Issue by Ruilkyu** [Tencent/bk-bcs#467]
对已经部署好了的kubernetes集群，可以使用平台管理该集群吗？

**Comment by DeveloperJim** [comment]
平台具备该能力。针对已经部署好的kubernetes集群，可以手动进行信息注册并部署bcs-kube-agent实现集群接入。
可以参考该说明: https://github.com/Tencent/bk-bcs/blob/1.17.x/docs/features/k8s/%E5%9F%BA%E4%BA%8Ek8s%E7%9A%84%E5%AE%B9%E5%99%A8%E7%BC%96%E6%8E%92.md#%E7%BA%B3%E7%AE%A1%E5%B7%B2%E6%9C%89-k8s-%E9%9B%86%E7%BE%A4
