### ISSUE TITLE
[bug]Makefile中使用了bash内置[[导致在/bin/sh指向dash时报错

### ISSUE THREAD

**Issue by chnliyong** [Tencent/bk-bcs#57]
问题描述
===========
在构建执行make命令时报错
```
if [[ ! -d ./vendor/github.com/sirupsen ]]; then ln -sf ./vendor/github.com/Sirupsen ./vendor/github.com/sirupsen; fi
/bin/sh: 1: [[: not found
if [[ ! -d ./vendor/github.com/Sirupsen ]]; then ln -sf ./vendor/github.com/sirupsen ./vendor/github.com/Sirupsen; fi
/bin/sh: 1: [[: not found
```

重现方法
================
在Ubuntu系统中（默认/bin/sh -> dash）执行构建make

关键信息
=========
Makefile中使用了bash的内置[[，在dash中不支持，CentOS默认/bin/sh -> bash，但是Ubuntu(或者Debian)中/bin/sh -> dash，在Ubuntu中将/bin/sh -> bash则不报错，或者将`[[`改成`[`也不报错。
请提供以下信息:

 - [x] bk-bcs   版本: 
Version  :bf46118-19.06.27
Tag      :bf46118
BuildTime:  2019-06-27T02:02:40+0000
GitHash:  bf46118f5ded63a52f4c4471615c1136e4343163
 - [x] 操作系统      :  `Ubuntu 18.04.2 LTS`
 - [x] bk-bcs 异常日志
无

**Comment by Lwxiang** [comment]
@chnliyong 感谢反馈，已经修复该问题
