### ISSUE TITLE
[DOCS文档] 增加BCS方案说明类文档、操作实战类文档 

### ISSUE THREAD

**Issue by Lwxiang** [Tencent/bk-bcs#83]
需要增加两类文档，放在 docs/features下，初步建议使用：

- docs/features/solutions （BCS方案说明）
- docs/features/practices （BCS操作实战文档）

**Comment by pythonton** [comment]
@Lwxiang 大锅~，**BCS操作实战文档**能否增加这2个：
- **BCS如何部署业界常见的应用**，如ELK、Grafana、Jenkins、WordPress等。
![image](https://user-images.githubusercontent.com/50493427/61865312-94f08a00-af05-11e9-9c7a-9299396a9560.png)
- **单体应用如何做微服务改造，并迁移至BCS**。
   其实我们想拥抱交付的变革，但不知道从何下手，前置项又是什么。
